import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { toPosix } from './paths.js';
import type { ScannedDoc } from './scan.js';
import type { RegistryResult, Workspace } from './types.js';

const START = '<!-- baab:registry:start -->';
const END = '<!-- baab:registry:end -->';

interface Member {
  id: string;
  title: string;
  type: string;
  status: string;
  /** Registry-relative link to the member's index. */
  link: string;
}

function fmString(doc: ScannedDoc, key: string, fallback = ''): string {
  const v = doc.frontmatter[key];
  return typeof v === 'string' ? v : fallback;
}

/** Members of a folder = the `_index.md` one level below it. */
function membersFor(folder: string, docs: ScannedDoc[]): Member[] {
  const prefix = `${folder}/`;
  const members: Member[] = [];
  for (const doc of docs) {
    if (!doc.relPath.startsWith(prefix)) continue;
    const rest = doc.relPath.slice(prefix.length);
    const parts = rest.split('/');
    // Match F/<child>/_index.md exactly (a spawned member's index).
    if (parts.length === 2 && parts[1] === '_index.md') {
      members.push({
        id: fmString(doc, 'id', parts[0]),
        title: doc.title,
        type: fmString(doc, 'type', 'unknown'),
        status: fmString(doc, 'status', 'unknown'),
        link: toPosix(`./${parts[0]}/_index.md`),
      });
    }
  }
  return members.sort((a, b) => a.id.localeCompare(b.id));
}

function renderBlock(folder: string, members: Member[]): string {
  const rows =
    members.length === 0
      ? '| _(none yet)_ | | | |'
      : members
          .map((m) => `| [${m.id}](${m.link}) | ${m.title} | ${m.type} | ${m.status} |`)
          .join('\n');
  const json = JSON.stringify(
    members.map((m) => ({
      id: m.id,
      title: m.title,
      type: m.type,
      status: m.status,
      path: m.link,
    })),
    null,
    2,
  );
  return [
    START,
    `<!-- Generated by \`baab index\` from the frontmatter of ${folder}/*/_index.md. Do not edit by hand. -->`,
    '',
    '| id | title | type | status |',
    '| --- | --- | --- | --- |',
    rows,
    '',
    '```json',
    json,
    '```',
    END,
  ].join('\n');
}

function seedRegistry(folder: string): string {
  const heading = folder.charAt(0).toUpperCase() + folder.slice(1);
  return [
    '---',
    'type: index',
    `id: ${folder}-registry`,
    'status: active',
    'created: 1970-01-01',
    'updated: 1970-01-01',
    'tags: [registry]',
    '---',
    '',
    `# ${heading} registry`,
    '',
    `Machine-readable roster of everything under \`${folder}/\`. The table and JSON`,
    'between the markers below are regenerated by `baab index` — edit the member',
    'files themselves, not this table.',
    '',
    START,
    END,
    '',
  ].join('\n');
}

/** Replace the fenced registry block, preserving prose outside the markers. */
function spliceBlock(existing: string, block: string): string {
  const s = existing.indexOf(START);
  const e = existing.indexOf(END);
  if (s === -1 || e === -1 || e < s) {
    // Markers missing/corrupt — append a fresh block.
    return `${existing.trimEnd()}\n\n${block}\n`;
  }
  return `${existing.slice(0, s)}${block}${existing.slice(e + END.length)}`;
}

/**
 * Regenerate `_registry.md` for every governed folder that hosts kinds, plus a
 * JSON export under `.baab/registries/<folder>.json`. Frontmatter is the source
 * of truth; the tables can never drift.
 */
export async function updateRegistries(ws: Workspace, docs: ScannedDoc[]): Promise<RegistryResult> {
  const folders = Object.entries(ws.config.folders)
    .filter(([, cfg]) => cfg.kinds.length > 0)
    .map(([name]) => name);

  const regDir = path.join(ws.stateDir, 'registries');
  await mkdir(regDir, { recursive: true });

  let rows = 0;
  for (const folder of folders) {
    const members = membersFor(folder, docs);
    rows += members.length;

    // The config may declare a governed folder the template never created
    // (custom templates). Materialize it so its registry has somewhere to live.
    await mkdir(path.join(ws.root, folder), { recursive: true });

    const regPath = path.join(ws.root, folder, '_registry.md');
    let existing: string;
    try {
      existing = await readFile(regPath, 'utf8');
    } catch {
      existing = seedRegistry(folder);
    }
    const block = renderBlock(folder, members);
    await writeFile(regPath, spliceBlock(existing, block), 'utf8');

    await writeFile(
      path.join(regDir, `${folder}.json`),
      `${JSON.stringify(
        members.map((m) => ({ id: m.id, title: m.title, type: m.type, status: m.status })),
        null,
        2,
      )}\n`,
      'utf8',
    );
  }

  return { folders, rows };
}
